url: https://tedxyouthvictoriapark.tk
baseurl: 

# Site settings
title: TEDxYouth@VictoriaPark
email: 
description: "An independently organized TED event"

collections:
    - speakers
    - team

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
    - title: facebook
      url: https://www.facebook.com/tedxyouthvictoriapark
    - title: instagram
      url: https://www.instagram.com/tedxyouthvictoriapark

# Build settings
host: 0.0.0.0
markdown: kramdown
permalink: pretty
compress_html:
    comments: all
