url: https://tedxyouthvictoriapark.ca

title: TEDxYouth@VictoriaPark
description: >-
  A youth-based TEDx organization in the Calgary area aimed towards exploring the issues, ideas and questions that are 
  central to young people today. We believe in providing an opportunity and platform for local youth to share their 
  novel and innovative ideas to their local and global communities.

collections:
  - speakers-2020
  - speakers-2019
  - team

# Build settings
host: 0.0.0.0
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-redirect-from
compress_html:
  comments: all
