url: https://tedxyouthvictoriapark.ca

title: TEDxYouth@VictoriaPark
description: "An independently organized TED event"

collections:
    - speakers
    - team

social:
    - title: facebook
      url: https://www.facebook.com/tedxyouthvictoriapark
    - title: instagram
      url: https://www.instagram.com/tedxyouthvictoriapark

# Build settings
host: 0.0.0.0
markdown: kramdown
permalink: pretty
compress_html:
    comments: all
